# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    remember-me:
      key: 97c7efb72e69386921ee26bbbbbfa75b22c6c2a4
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: jhipsterWebsocketSampleApplication
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
